/**
 * buildDefaultSessionName.ts — Nombre autogenerado para sesiones (B15 / D19)
 *
 * Lógica pura — sin DOM ni RTK. Ver docs/feedback/b15-autonombre-sesion/05_VERIFICACIONES_TECNICAS.md
 *
 * @author Frontend Team
 * @since v6.8.0 — B15 Autonombre sesión
 */

export interface BuildDefaultSessionNameInput {
    /** YYYY-MM-DD */
    sessionDate: string;
    /** Label ES de cualidad (ya resuelto desde catálogo) */
    qualityLabel?: string | null;
    /** Primer patrón del día — name_es */
    primaryPatternLabel?: string | null;
    /** Sesión libre sin plan activo */
    isStandalone?: boolean;
    /** Instanciar plantilla de sesión */
    templateName?: string | null;
    locale?: string;
}

const NAME_SEPARATOR = " · ";

function parseLocalDate(iso: string): Date | null {
    const [y, m, d] = iso.split("-").map(Number);
    if ([y, m, d].some((n) => Number.isNaN(n))) return null;
    const dt = new Date(y, m - 1, d);
    if (Number.isNaN(dt.getTime())) return null;
    if (dt.getFullYear() !== y || dt.getMonth() !== m - 1 || dt.getDate() !== d) return null;
    return dt;
}

const WEEKDAY_SHORT_ES = ["dom", "lun", "mar", "mié", "jue", "vie", "sáb"] as const;
const MONTH_SHORT_ES = [
    "ene", "feb", "mar", "abr", "may", "jun",
    "jul", "ago", "sep", "oct", "nov", "dic",
] as const;

/**
 * Fecha corta estable — ej. «mié 24 jun» (independiente del locale del SO)
 */
export function formatSessionDateShort(
    sessionDate: string,
    locale = "es-ES",
): string {
    const dt = parseLocalDate(sessionDate);
    if (!dt) return sessionDate;

    if (locale === "es-ES") {
        const dow = WEEKDAY_SHORT_ES[dt.getDay()];
        const day = dt.getDate();
        const mon = MONTH_SHORT_ES[dt.getMonth()];
        return `${dow} ${day} ${mon}`;
    }

    return dt.toLocaleDateString(locale, {
        weekday: "short",
        day: "numeric",
        month: "short",
    });
}

function slugToTitleCase(slug: string): string {
    return slug
        .replace(/_/g, " ")
        .replace(/\b\w/g, (c) => c.toUpperCase());
}

function normalizeSessionName(value: string): string {
    return value.trim().replace(/\s+/g, " ");
}

function joinSegments(segments: Array<string | null | undefined>): string {
    return segments
        .map((s) => s?.trim())
        .filter((s): s is string => Boolean(s && s.length > 0))
        .join(NAME_SEPARATOR);
}

/**
 * Nombre por defecto para sesión de calendario.
 */
export function buildDefaultSessionName(input: BuildDefaultSessionNameInput): string {
    const {
        sessionDate,
        qualityLabel,
        primaryPatternLabel,
        isStandalone = false,
        templateName,
        locale = "es-ES",
    } = input;

    const dateShort = formatSessionDateShort(sessionDate, locale);

    if (templateName?.trim()) {
        return joinSegments([templateName.trim(), dateShort]);
    }

    if (isStandalone) {
        return joinSegments(["Sesión libre", dateShort]);
    }

    const quality =
        qualityLabel?.trim() ||
        null;

    return joinSegments([
        quality,
        primaryPatternLabel,
        dateShort,
    ]) || joinSegments(["Sesión", dateShort]);
}

/**
 * True si el nombre guardado coincide con el autogenerado para los mismos inputs.
 */
export function isAutoGeneratedSessionName(
    name: string,
    input: BuildDefaultSessionNameInput,
): boolean {
    const normalized = normalizeSessionName(name);
    if (!normalized) return false;
    return normalized === normalizeSessionName(buildDefaultSessionName(input));
}

export { slugToTitleCase, normalizeSessionName };

export function resolvePhysicalQualityLabel(
    slug: string,
    catalog: ReadonlyArray<{ slug: string; name: string }>,
): string {
    const found = catalog.find((q) => q.slug === slug);
    if (found?.name) return found.name;
    return slugToTitleCase(slug);
}
