import { describe, it, expect } from "vitest";
import {
    buildDefaultSessionName,
    formatSessionDateShort,
    isAutoGeneratedSessionName,
} from "./buildDefaultSessionName";

describe("formatSessionDateShort", () => {
    it("formats YYYY-MM-DD in es-ES", () => {
        const formatted = formatSessionDateShort("2026-06-24", "es-ES");
        expect(formatted.toLowerCase()).toContain("24");
        expect(formatted.toLowerCase()).toMatch(/mi[ée]/);
    });
});

describe("buildDefaultSessionName", () => {
    it("includes quality, pattern and short date", () => {
        const name = buildDefaultSessionName({
            sessionDate: "2026-06-24",
            qualityLabel: "Hipertrofia",
            primaryPatternLabel: "Empuje horizontal",
        });
        expect(name).toBe("Hipertrofia · Empuje horizontal · mié 24 jun");
    });

    it("omits pattern segment when absent", () => {
        const name = buildDefaultSessionName({
            sessionDate: "2026-06-24",
            qualityLabel: "Hipertrofia",
        });
        expect(name).toBe("Hipertrofia · mié 24 jun");
    });

    it("standalone session uses Sesión libre prefix", () => {
        const name = buildDefaultSessionName({
            sessionDate: "2026-06-24",
            isStandalone: true,
        });
        expect(name).toBe("Sesión libre · mié 24 jun");
    });

    it("template instantiate uses template name and date", () => {
        const name = buildDefaultSessionName({
            sessionDate: "2026-06-24",
            templateName: "Pierna A",
        });
        expect(name).toBe("Pierna A · mié 24 jun");
    });

    it("falls back safely for invalid date", () => {
        const name = buildDefaultSessionName({
            sessionDate: "not-a-date",
            qualityLabel: "Fuerza",
        });
        expect(name).toContain("Fuerza");
        expect(name).toContain("not-a-date");
    });
});

describe("isAutoGeneratedSessionName", () => {
    it("returns true for matching auto name", () => {
        const input = {
            sessionDate: "2026-06-24",
            qualityLabel: "Hipertrofia",
        };
        const auto = buildDefaultSessionName(input);
        expect(isAutoGeneratedSessionName(auto, input)).toBe(true);
    });

    it("returns false for custom name", () => {
        expect(
            isAutoGeneratedSessionName("Mi sesión especial", {
                sessionDate: "2026-06-24",
                qualityLabel: "Hipertrofia",
            }),
        ).toBe(false);
    });
});
