/**
 * sessionProgramming utils — Utilidades para Session Programming
 *
 * @author Frontend Team
 * @since v5.3.0
 */

export { buildTrainingSessionCreate } from "./buildTrainingSessionCreate";
export type { BuildTrainingSessionCreateParams } from "./buildTrainingSessionCreate";
export {
    getCaracterTipoFromEffortCharacter,
    getEffortCharacterForCaracterTipo,
} from "./effortCharacterMapping";
export type { CaracterTipo } from "./effortCharacterMapping";
export {
    suggestNextSessionDateAfter,
    suggestSessionDateForPeriodBlock,
} from "./suggestSessionDate";
export type { SessionDateCarrier } from "./suggestSessionDate";
export {
    defaultSessionCreateKind,
    parseSessionCreateKindParam,
} from "./resolveSessionCreateKind";
export type { SessionCreateKind } from "./resolveSessionCreateKind";
export { buildCreateSessionQueryFromBlock } from "./buildCreateSessionQueryFromBlock";
export type { BuildCreateSessionQueryFromBlockInput } from "./buildCreateSessionQueryFromBlock";
export {
    resolveCreateSessionClientContext,
} from "./resolveCreateSessionClientContext";
export type { CreateSessionClientPlanContext } from "./resolveCreateSessionClientContext";
export {
    buildDefaultSessionName,
    formatSessionDateShort,
    isAutoGeneratedSessionName,
    slugToTitleCase,
    normalizeSessionName,
    resolvePhysicalQualityLabel,
} from "./buildDefaultSessionName";
export type { BuildDefaultSessionNameInput } from "./buildDefaultSessionName";
export {
    clampSessionDateToPlan,
    pickDefaultTrainingPlanId,
    resolveSessionDateBoundsForPlan,
    suggestDefaultSessionDateForPlan,
    validateSessionDateWithinPlan,
} from "./sessionPlanDateBounds";
export type {
    SessionDateBounds,
    TrainingPlanDateRange,
    TrainingPlanPickerLike,
} from "./sessionPlanDateBounds";





